name: Analyze with CodeGuru Reviewer

on: 
 - push
 - workflow_dispatch # This allows manual triggering of the action through the GitHub UI.

permissions:
    id-token: write
    contents: read
    security-events: write 

jobs:
  build:
    name: Analyze with CodeGuru Reviewer
    runs-on: self-hosted
    steps:
  
    
    - uses: actions/checkout@v2
     
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
     
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
   

    - name: CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@v1.1
      
      with:          
        s3_bucket: codeguru-reviewer-mybucketnew
        
      env:
        AWS_DEFAULT_REGION: us-west-2
        AWS_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Store SARIF file
     
      uses: actions/upload-artifact@v2
      with:
        name: SARIF_recommendations
        path: ./codeguru-results.sarif.json

    - name: Upload review result
     
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
